# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180416_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
